apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  namespace: cake-delight
  labels:
    app: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:3-management
          ports:
            - containerPort: 5672
              name: amqp
            - containerPort: 15672
              name: management
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: cake-delight
spec:
  selector:
    app: rabbitmq
  ports:
    - port: 5672 # this is the port that the service will expose within the cluster
      targetPort: 5672 # this is the port that the container is listening on
      name: amqp # amqp is the name of the port that will be used to access the RabbitMQ message broker
    - port: 15672 # this is the port that the service will expose within the cluster
      targetPort: 15672 # this is the port that the container is listening on
      name: management # management is the name of the port that will be used to access the RabbitMQ management interface
  type: ClusterIP #this is the type of service that will be created, ClusterIP means that the service will only be accessible within the cluster
