apiVersion: apps/v1
kind: Deployment
metadata:
  name: rating-service
  namespace: cake-delight
  labels:
    app: rating-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rating-service
  template:
    metadata:
      labels:
        app: rating-service
    spec:
      containers:
        - name: rating-service
          image: rating-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 3002
          env:
            - name: PORT
              value: "3002"
            - name: MONGODB_URI
              value: "mongodb://mongodb.cake-delight.svc.cluster.local:27017/cakedelight-rating" # cadelight-rating is the name of the database for the rating service, this provide the logical separation of data between the catalog, rating and other services. 
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "250m"
---
apiVersion: v1
kind: Service
metadata:
  name: rating-service
  namespace: cake-delight
spec:
  selector:
    app: rating-service
  ports:
    - port: 3002
      targetPort: 3002
  type: ClusterIP
