apiVersion: apps/v1
kind: Deployment
metadata:
  name: client
  namespace: cake-delight
  labels:
    app: client
spec:
  replicas: 2
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
        - name: client
          image: client:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "100m"
---
apiVersion: v1
kind: Service
metadata:
  name: client
  namespace: cake-delight
spec:
  selector:
    app: client
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30000
  type: NodePort
